### ISSUE TITLE
Add build to Travis CI automatically

### ISSUE THREAD

**Issue by bdw429s** [elpete/cb-module-template#2]
I don't really know if this is possible or not and it may require some separate auth token from Travis, but it would be cool if the `travis.yml` file was just automatically picked up and the Travis CI build started running right away without needing to go to the Travis site and activating the build.  This would probably require the user to already have a Travis account connected to Github.

**Comment by elpete** [comment]
See https://docs.travis-ci.com/api#with-a-github-token

**Comment by elpete** [comment]
Flow:
1. Use GitHub Token to get a Travis Token.
2. Store Travis Token
3. Get repo id on Travis ( `GET /repos/:user/:repo` )
4. Start hooks ( `PUT /hooks { "repo": { "id": "{repo_id}", "active": true }` )
